
---
- name: Provision VM
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/test.yml
    

  tasks:
          
- name: Create VMs
  win_hyperv_guest:
    name: "{{item.name}}"
    generation: "{{defaut_generation}}"
    cpu: "{{item.cpu}}"
    memory: "{{item.memory}}"
    network_switch: "{{item.network_switch}}"
    diskpath: "{{item.dest_vhd}}"
    state: present
  with_items: "{{ vms }}"
  register: new_vms

- name: Poweron VMs
  win_hyperv_guest:
    name: "{{item.name}}"
    state: started 
  with_items: "{{ vms }}"
